services:
  - type: web
    name: sentiment-api
    env: python
    rootDir: backend   # since your project root is inside backend/
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
